### ISSUE TITLE
need to add more error handling

### ISSUE THREAD

**Issue by chrisalrutz** [chrisalrutz/vinyl#3]

**Comment by chrisalrutz** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in get_City
  File "<stdin>", line 33, in get_Inventory
  File "/home/chris/.local/lib/python3.9/site-packages/oauth2/__init__.py", line 685, in request
    return httplib2.Http.request(self, uri, method=method, body=body,
  File "/home/chris/.local/lib/python3.9/site-packages/httplib2/__init__.py", line 1701, in request
    (response, content) = self._request(
  File "/home/chris/.local/lib/python3.9/site-packages/httplib2/__init__.py", line 1421, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/chris/.local/lib/python3.9/site-packages/httplib2/__init__.py", line 1344, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by chrisalrutz** [comment]
moving to scrapy solved this error
